{'env': 'NlHoldemEnvWithOpponent',
 'train_batch_size': 1000,
 'num_gpus': 0,
 'gamma': 1,
 'entropy_coeff': 0.1,
 'lr': 0.0003,
 'model': {'custom_model': 'NlHoldemLgNet',
           'max_seq_len': 20,
           'custom_model_config': {}},
 'env_config': {'custom_options': {'rwd_ratio': 1.0, 'num_players': 6}},
 'num_env_runners': 2,
 'num_envs_per_env_runner': 1,
 'rollout_fragment_length': 50}
