{'env': 'NlHoldemEnvWithOpponent',
 'rollout_fragment_length': 50,
 'train_batch_size': 4000,
 'num_envs_per_env_runner': 1,
 'num_gpus': 0,
 'gamma': 1,
 'entropy_coeff': 0.1,
 'lr': 0.0003,
 'model': {'custom_model': 'NlHoldemStructuredNet',
           'custom_model_config': {'relative_seats': True, 'separate_critic': True}},
 'env_config': {'custom_options': {'history_len': 20,
                                   'num_players': 6,
                                   'betting_features': True}},
 'num_env_runners': 2}
